# Generated by Django 5.1.2 on 2024-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
